config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 root to: 'finder#index'

 get 'alphabetized' => 'finder#alphabetized', as: 'alphabetized'
 get 'missing_email' => 'finder#missing_email', as: 'missing_email'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/finder_controller.rb
class FinderController < ApplicationController
	def index
		@page_title = "All Customers"
		@customers = Customer.all
	end
	# the @customers variable will now be acessible from
	# the automatically loaded view: app/views/finder/index.html.erb


	def alphabetized
		@page_title = "Alphabetized customers"
		@customers = Customer.order(:full_name)
		render :index
	end

	def missing_email
		@page_title = "Missing_email customers"
		@customers = Customer.where(email_address:'')
		render :index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/finder_helper.rb
module FinderHelper
end

app/views/customers/_customer.html.erb
<div class = "customer">
<h2><%=customer.full_name%></h2>
<p><strong>Phone Number:</strong><%=customer.phone_number%></p>
<p><strong>Email Address:</strong><%=customer.email_address%></p>
</div>

app/views/finder/index.html.erb
<h2><%= @page_title%></h2>
<% if @customers.size.zero? %>
<p> No Customers Found </p>
<%else%>
<%= render @customers%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  <nav>
  <ul>
  <li>
  	<%= link_to 'Home',root_path%>
  </li>

  <li>
  	<%= link_to 'Alphabetized',alphabetized_path%>
  </li>

    <li>
  	<%= link_to 'Missing_email',missing_email_path%>
  </li>


  </ul>
  </nav>
  </header>
    <%= yield %>
  </body>
</html>